---
- hosts: all
  gather_facts: no
  connection: local
  vars:
    user: admin
    output: ./outputs/{{ inventory_hostname }}
  tasks:
    - name: ping
      ping:

    - name: create output dirs
      file:
        state: directory
        path: "{{ output }}"

    - name: generate ip
      template:
        src: ./templates/ip.auto.rsc.j2
        dest: "{{ output }}/ip.auto.rsc"
      notify: upload ip

    - name: generate ospf
      template:
        src: ./templates/ospf.auto.rsc.j2
        dest: "{{ output }}/ospf.auto.rsc"
      notify: upload ospf

    - name: generate ldp
      template:
        src: ./templates/ldp.auto.rsc.j2
        dest: "{{ output }}/ldp.auto.rsc"
      notify: upload ldp

  handlers:
    - name: upload ip
      shell: "curl -T {{ output }}/ip.auto.rsc ftp://{{ user }}@{{ansible_host}}"

    - name: upload ospf
      shell: "curl -T {{ output }}/ospf.auto.rsc ftp://{{ user }}@{{ansible_host}}"

    - name: upload ldp
      shell: "curl -T {{ output }}/ldp.auto.rsc ftp://{{ user }}@{{ansible_host}}"

