---

ip:
  - name: loopback
    address: 3.3.3.3/32
  - name: ether2
    address: 10.13.0.3/24
  - name: ether3
    address: 10.23.0.3/24

bgp:
  asn: 65500
  peers:
    - name: edge-4
      asn: 65500

