---

ip:
  - name: loopback
    address: 3.3.3.3/32
  - name: ether2
    address: 10.13.0.3/24
  - name: ether3
    address: 10.23.0.3/24
  - name: ether4
    address: 10.35.0.3/24

bgp:
  asn: 65500
  peers:
    - name: edge-4
      address: 4.4.4.4
      asn: 65500
      af:
        - vpnv4

vrf:
  - name: site-a
    rd: 3.3.3.3:1
    export:
      - 3.3.3.3:1
    import:
      - 4.4.4.4:1
    interfaces:
      - ether4

