---

ip:
  - name: loopback
    address: 4.4.4.4/32
  - name: ether2
    address: 10.24.0.4/24
  - name: ether3
    address: 10.14.0.4/24
  - name: ether4
    address: 10.46.0.4/24

bgp:
  asn: 65500
  peers:
    - name: edge-3
      address: 3.3.3.3
      asn: 65500
      af:
        - vpnv4
        - ip

vrf:
  - name: site-a
    rd: 4.4.4.4:1
    exports:
      - 4.4.4.4:1
    imports:
      - 3.3.3.3:1
    interfaces:
      - ether4

