---
- hosts: all
  gather_facts: no
  connection: local
  vars:
    output: ../outputs/{{ inventory_hostname }}
  tasks:
    - name: create output template directories
      file:
        state: directory
        path: "{{ output }}"

