---
- hosts: all
  gather_facts: no
  connection: local
  vars:
    user: admin
    output: ../outputs/{{ inventory_hostname }}
  tasks:
    - name: generate ospf
      template:
        src: ../templates/ospf.auto.rsc.j2
        dest: "{{ output }}/ospf.auto.rsc"
      notify: upload ospf

  handlers:
    - name: upload ospf
      shell: "curl -T {{ output }}/ospf.auto.rsc ftp://{{ user }}@{{ansible_host}}"

